"""Fix types for journal_entries

Revision ID: 14f1c340d7c2
Revises: 51ae68b2aff1
Create Date: 2025-06-17 22:51:16.153851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f1c340d7c2'
down_revision: Union[str, Sequence[str], None] = '51ae68b2aff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade():
    # Convert entry_date to DATE
    op.execute("""
        ALTER TABLE journal_entries
        ALTER COLUMN entry_date
        TYPE DATE
        USING entry_date::DATE
    """)

    # Convert sentiment_score to FLOAT
    op.execute("""
        ALTER TABLE journal_entries
        ALTER COLUMN sentiment_score
        TYPE FLOAT
        USING sentiment_score::FLOAT
    """)

    # Convert created_at to TIMESTAMP
    op.execute("""
        ALTER TABLE journal_entries
        ALTER COLUMN created_at
        TYPE TIMESTAMP
        USING created_at::TIMESTAMP
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('journal_entries', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('journal_entries', 'sentiment_score',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('journal_entries', 'entry_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
