"""Add journal_entries table

Revision ID: 51ae68b2aff1
Revises: 
Create Date: 2025-06-17 22:41:07.902794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51ae68b2aff1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('journal_entries', 'entry_date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('journal_entries', 'entry',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('journal_entries', 'sentiment_score',
               existing_type=sa.NUMERIC(precision=5, scale=4),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('journal_entries', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    op.drop_constraint(op.f('journal_entries_user_id_fkey'), 'journal_entries', type_='foreignkey')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_column('users', 'email')
    op.drop_column('users', 'stress_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stress_level', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'])
    op.create_foreign_key(op.f('journal_entries_user_id_fkey'), 'journal_entries', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.alter_column('journal_entries', 'created_at',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('journal_entries', 'sentiment_score',
               existing_type=sa.String(),
               type_=sa.NUMERIC(precision=5, scale=4),
               existing_nullable=True)
    op.alter_column('journal_entries', 'entry',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('journal_entries', 'entry_date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
